config/routes.rb
Todo::Application.routes.draw do
  
  resources :todo_items
  root :to => redirect { |p, req| req.flash.keep; "/all" }

  match '/new' => "todo_items#new"

  match '/all'            => 'todo_items#index'
  match '/all/incomplete' => 'todo_items#index', :completed => false
  match '/all/complete'   => 'todo_items#index', :completed => true

  match '/todo_items/complete/:id' => 'todo_items#complete'

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  attr_accessible :completed, :notes, :title
  validates_presence_of :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  # GET /todo_items
  # GET /todo_items.json
  def index

    if params.has_key? :completed
      @todo_items = TodoItem.where(:completed => params[:completed])
    else
      @todo_items = TodoItem.order(:completed)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @todo_items }
    end
  end

  # GET /todo_items/1
  # GET /todo_items/1.json
  def show
    begin
      @todo_item = TodoItem.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "To-Do item not found"
      return redirect_to :action => 'index'
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @todo_item }
    end
  end

  # GET /todo_items/new
  # GET /todo_items/new.json
  def new
    @todo_item = TodoItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @todo_item }
    end
  end

  # GET /todo_items/1/edit
  def edit
    @todo_item = TodoItem.find(params[:id])
  end

  # POST /todo_items
  # POST /todo_items.json
  def create
    @todo_item = TodoItem.new(params[:todo_item])

    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to @todo_item, :notice => 'Todo item was successfully created.' }
        format.json { render :json => @todo_item, :status => :created, :location => @todo_item }
      else
        format.html { render :action => "new" }
        format.json { render :json => @todo_item.errors, :status => :unprocessable_entity }
      end
    end
  end  

  # PUT /todo_items/1
  # PUT /todo_items/1.json
  def update
    @todo_item = TodoItem.find(params[:id])

    respond_to do |format|
      if @todo_item.update_attributes(params[:todo_item])
        format.html { redirect_to @todo_item, :notice => 'Todo item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @todo_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /todo_items/complete/1
  def complete
    @todo_item = TodoItem.find(params[:id])

    @todo_item.update_attribute(:completed, params[:completed])

    head :no_content

  end;

  # DELETE /todo_items/1
  # DELETE /todo_items/1.json
  def destroy
    @todo_item = TodoItem.find(params[:id])
    @todo_item.destroy

    respond_to do |format|
      format.html { redirect_to todo_items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>To-Do List</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body onload="mark_page_dirty()">

<div class="container-narrow">

  <div class="masthead">
    <ul class="nav nav-pills pull-right">
      <li><a href="/all">All</a></li>
      <li><a href="/all/incomplete">Incomplete</a></li>
      <li><a href="/all/complete">Complete</a></li>
      <li><a href="/new" class="btn btn-info"><i class="icon-white icon-plus"></i> New Todo</a></li>
    </ul>
    <h3 class="muted"><a href="/">To-Do List</a></h3>
  </div>

  <hr>

  <% if flash[:notice] %>
    <div class="alert alert-success"><%= notice %></div>
  <% end
    if flash[:error] %>
    <div class="alert alert-error"><%= flash[:error] %></div>
  <% end %>

  <div class="row-fluid">

  	<%= yield %>

  </div>

  <hr>

</div>
<form name="back_detector">
  <input type="hidden" id="page_is_dirty" name="page_is_dirty" value="0" />
</form>
</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for @todo_item do |f| %>

  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>
      <ul>
      <% @todo_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="page-header row-fluid todo-item">
    <div class="span1">
      <%= f.check_box :completed, :class => 'regular-checkbox' %>
      <%= f.label :completed, raw("&nbsp;"), :style => 'margin-left: 11px' %>
    </div>
    <div class="span11">
      <%= f.text_field :title, :class => 'span12', :style => 'font-size: 24px', :placeholder => 'Title' %>
    </div>
  </div> 
  <div class="control-group">
    <div class="controls">
      <%= f.text_area :notes, :placeholder => "Notes", :class => "span12" %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit :class => 'btn btn-primary', :disable_with => "Saving..." %>
    <%= if params[:action] != 'new'
      link_to raw('<i class="icon-chevron-left"></i> Back'), @todo_item, :class => 'btn'
    end %>
    <%= link_to raw('<i class="icon-th-list"></i> List'), todo_items_path, :class => 'btn' %>
    <%= if params[:action] != 'new'
        link_to raw('<i class="icon-trash icon-white"></i>&nbsp;Delete'), @todo_item, :method => :delete, :class => 'btn btn-danger'
      end %> 
  </div>
<% end %>
<script>
  $('#todo_item_title').focus();
</script>

app/views/todo_items/edit.html.erb
<h2 class="page-header">Editing Todo Item</h2>

<%= render 'form' %>

app/views/todo_items/index.html.erb
<h2 class="page-header"><%= params[:completed] == nil ? 'All' : (params[:completed] == true ? 'Completed' : 'Incomplete') %> Todos</h2>

<table class="table table-striped todo-list">

  <thead>
    <tr>
      <th>Check</th>
      <th>Title</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @todo_items.each do |todo| %>
      <tr data-id="<%= todo.id.to_s %>">
        <td>
          <%= check_box_tag "todo_item[" + todo.id.to_s + "][completed]", "1", todo.completed, :class => 'regular-checkbox' %>
          <%= label "todo_item[" + todo.id.to_s + "]", "completed", raw("&nbsp;") %>
          <%= hidden_field_tag("todo_item[" + todo.id.to_s + "][completed][id]", todo.id) %>
        </td>
        <td>
          <%= link_to todo.title, todo, :class => (todo.completed ? 'complete' : 'incomplete') %>
        </td>
        <td>
          <%= link_to raw('<i class="icon-pencil"></i>'), edit_todo_item_path(todo), :class => "btn" %>
        </td>
        <td>
          <%= link_to raw('<i class="icon-white icon-trash"></i>'), todo, :method => :delete, :class => "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>

</table>

<% unless @todo_items.empty? %>
  <div class="well multi-actions">
    <button class="btn check-all"><i class="icon-check"> &nbsp;Complete All</i></button>&nbsp;
    <button class="btn uncheck-all"><i class="icon-check-empty"> &nbsp;Uncomplete All</i></button>
  </div>
<% end %>

<div id="no-incomplete"<%= @todo_items.empty? && params[:completed] == false ? '' : raw(' style="display: none;"') %>>
  <div class="cake pull-left"></div>
  <h5>Congratulations, you completed everything! <br>Here's some cake to celebrate.</h5>
</div>

<div id="no-todos"<%= @todo_items.empty? && params[:completed] == nil ? '' : raw(' style="display: none;"') %>>
  <h5>Oh no, you've run out of things to do! Quickly, <%= link_to raw('Create a new one <i class="icon-chevron-right"></i>'), new_todo_item_path, :class => "btn btn-info" %></h5>
</div>
  
<div id="no-complete"<%= @todo_items.empty? && params[:completed] == true ? '' : raw(' style="display: none;"') %>>
  <h5>Looks like you haven't completed anything. Better get to work!</h5>
</div>

app/views/todo_items/new.html.erb
<h2 class="page-header">New Todo Item</h2>

<%= render 'form' %>

app/views/todo_items/show.html.erb
<div class="page-header row-fluid todo-item">
	<div class="span1">
      <%= check_box_tag "todo_item[" + @todo_item.id.to_s + "][completed]", "1", @todo_item.completed, :class => 'regular-checkbox' %>
      <%= label "todo_item[" + @todo_item.id.to_s + "]", "completed", raw("&nbsp;"), :style => 'margin-top: 16px; margin-left: 13px' %>
      <%= hidden_field_tag("todo_item[" + @todo_item.id.to_s + "][completed][id]", @todo_item.id) %>
    </div>
    <div class="span11">
      <h3<%= if @todo_item.completed?
          raw(' class="complete"')
          end %>><%= @todo_item.title %></h3>
    </div>
</div>

<% unless @todo_item.notes.empty? %>
	<p><%= @todo_item.notes %></p>
<% end %>

<div class="form-actions">
	<%= link_to raw('<i class="icon-chevron-left"></i> Back'), todo_items_path, :class => 'btn'%>
	<%= link_to raw('<i class="icon-pencil"></i> Edit'), edit_todo_item_path(@todo_item), :class => 'btn' %> 
  <%= link_to raw('<i class="icon-trash icon-white"></i>&nbsp;Delete'), @todo_item, :method => :delete, :class => 'btn btn-danger' %> 
</div>